-- Database Creation and Insert

Use IT488_USPS2

create table Customers_List 
(
	Customer_ID Int Not Null Identity(1,1) Primary Key,
	Customer_FirstName NVARCHAR(50),
	Customer_LastName NVARCHAR(50),
	Customer_DateOfBirth DATE,
	Customer_Phone NVARCHAR(15),
	Customer_Email NVARCHAR(50),
	Customer_Address NVARCHAR(50),
	Customer_City NVARCHAR(25),
	Customer_State NVARCHAR(2),
	Customer_ZipCode NVARCHAR(10),
	Customer_UserName NVARCHAR(50),
	Customer_Password NVARCHAR(50),
	Doctor_ID Int,
	Prescription_ID Int,
	Customer_Payment_ID Int,
	Drug_Allergy_ID Int,
);

Use IT488_USPS2

insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Isidoro', 'Domenici', '1949-06-21', '540-801-9539', 'idomenici0@ning.com', '93 Mariners Cove Plaza', 'Roanoke', 'VA', '24009', 'idomenici0');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Gusti', 'Mayhew', '1946-04-16', '972-147-8394', 'gmayhew1@netscape.com', '86140 Sachtjen Point', 'Dallas', 'TX', '75205', 'gmayhew1');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Aura', 'Sheldrick', '1959-12-29', '601-422-5042', 'asheldrick2@virginia.edu', '340 Stephen Drive', 'Jackson', 'MS', '39216', 'asheldrick2');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Aluino', 'Hanks', '1954-07-10', '713-887-9937', 'ahanks3@ustream.tv', '4760 Merry Street', 'Houston', 'TX', '77271', 'ahanks3');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Iago', 'Summerlee', '1988-10-18', '713-430-4439', 'isummerlee4@sbwire.com', '28 Katie Junction', 'Houston', 'TX', '77240', 'isummerlee4');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Rodney', 'Twentyman', '1946-10-21', '216-668-5673', 'rtwentyman5@behance.net', '0112 Dovetail Place', 'Cleveland', 'OH', '44111', 'rtwentyman5');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Rodrick', 'Cowell', '1959-01-29', '203-649-9708', 'rcowell6@linkedin.com', '98278 Cambridge Circle', 'New Haven', 'CT', '06538', 'rcowell6');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Roxanna', 'Roller', '1971-02-18', '859-809-9080', 'rroller7@wunderground.com', '19539 Oak Street', 'Lexington', 'KY', '40515', 'rroller7');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Jordain', 'Stooke', '1975-11-27', '304-573-3958', 'jstooke8@indiegogo.com', '77409 Tennyson Alley', 'Huntington', 'WV', '25716', 'jstooke8');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Jean', 'Thunnercliffe', '1973-07-06', '915-452-5358', 'jthunnercliffe9@ycombinator.com', '163 Wayridge Point', 'El Paso', 'TX', '79977', 'jthunnercliffe9');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Keefer', 'Elphinstone', '1975-01-15', '352-308-6005', 'kelphinstonea@weather.com', '15439 Kinsman Alley', 'Ocala', 'FL', '34479', 'kelphinstonea');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Eugenius', 'Lambertini', '1984-06-06', '915-988-1230', 'elambertinib@theglobeandmail.com', '260 Maywood Center', 'El Paso', 'TX', '88574', 'elambertinib');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('La verne', 'Spadaro', '1960-08-12', '904-550-9607', 'lspadaroc@irs.gov', '24 Duke Crossing', 'Jacksonville', 'FL', '32204', 'lspadaroc');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Giselbert', 'Geri', '1986-01-26', '406-802-6953', 'ggerid@yahoo.co.jp', '28412 4th Alley', 'Helena', 'MT', '59623', 'ggerid');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Elwyn', 'Scollan', '1999-05-16', '813-710-9638', 'escollane@kickstarter.com', '1479 Lunder Trail', 'Tampa', 'FL', '33647', 'escollane');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Dacey', 'Hakking', '1982-11-16', '913-238-9712', 'dhakkingf@4shared.com', '267 Dottie Parkway', 'Shawnee Mission', 'KS', '66286', 'dhakkingf');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Aron', 'Birdsall', '1991-12-09', '704-826-0145', 'abirdsallg@symantec.com', '855 Pleasure Point', 'Gastonia', 'NC', '28055', 'abirdsallg');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Laverne', 'Soppit', '1980-04-12', '478-713-8434', 'lsoppith@acquirethisname.com', '4622 Brickson Park Court', 'Macon', 'GA', '31296', 'lsoppith');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Archaimbaud', 'Dayce', '1964-04-19', '801-491-8022', 'adaycei@amazon.de', '7876 Barnett Plaza', 'Ogden', 'UT', '84409', 'adaycei');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('De', 'Andraud', '1949-06-16', '202-664-5715', 'dandraudj@cnet.com', '8 Superior Park', 'Washington', 'DC', '20073', 'dandraudj');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Mabel', 'Loftus', '1996-06-08', '616-807-4876', 'mloftusk@netscape.com', '08723 Blackbird Crossing', 'Grand Rapids', 'MI', '49544', 'mloftusk');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Kassey', 'Trittam', '1983-05-01', '864-441-5810', 'ktrittaml@deviantart.com', '55668 Canary Street', 'Spartanburg', 'SC', '29305', 'ktrittaml');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Phil', 'Twidle', '1992-07-24', '859-682-4085', 'ptwidlem@earthlink.net', '51 Kensington Circle', 'Lexington', 'KY', '40586', 'ptwidlem');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Nicolette', 'Haslin', '1981-01-05', '412-715-7379', 'nhaslinn@wordpress.com', '2971 Ilene Street', 'Pittsburgh', 'PA', '15230', 'nhaslinn');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Jodie', 'Bakey', '1999-09-24', '203-230-0394', 'jbakeyo@t-online.de', '1415 Helena Street', 'Fairfield', 'CT', '06825', 'jbakeyo');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Erika', 'Duberry', '1974-11-16', '773-291-5453', 'eduberryp@cnn.com', '62075 Little Fleur Avenue', 'Chicago', 'IL', '60609', 'eduberryp');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Brett', 'Thomasen', '1954-05-16', '817-888-7897', 'bthomasenq@mit.edu', '78760 Schmedeman Way', 'Fort Worth', 'TX', '76121', 'bthomasenq');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Giuditta', 'Spink', '1986-10-04', '817-126-3579', 'gspinkr@alexa.com', '46 Cordelia Lane', 'Arlington', 'TX', '76011', 'gspinkr');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Lucinda', 'De Michetti', '1997-10-05', '410-802-0095', 'ldemichettis@hostgator.com', '73 Browning Terrace', 'Ridgely', 'MD', '21684', 'ldemichettis');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Moise', 'Lemary', '1997-08-05', '909-330-8501', 'mlemaryt@opera.com', '76 Tennyson Terrace', 'San Bernardino', 'CA', '92415', 'mlemaryt');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Cal', 'Dameisele', '1990-12-14', '954-403-8415', 'cdameiseleu@engadget.com', '653 Fisk Circle', 'Fort Lauderdale', 'FL', '33330', 'cdameiseleu');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Teddie', 'Itshak', '1968-08-20', '602-501-8979', 'titshakv@sina.com.cn', '7851 Iowa Point', 'Phoenix', 'AZ', '85067', 'titshakv');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Catlaina', 'McAlinden', '1950-07-06', '520-320-0321', 'cmcalindenw@about.com', '0 Ruskin Street', 'Tucson', 'AZ', '85737', 'cmcalindenw');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Bronnie', 'Garroway', '1989-11-15', '336-454-9404', 'bgarrowayx@furl.net', '00144 Acker Trail', 'Winston Salem', 'NC', '27110', 'bgarrowayx');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Mariquilla', 'Brandolini', '1950-12-13', '202-597-8264', 'mbrandoliniy@indiegogo.com', '41730 Butternut Way', 'Washington', 'DC', '20244', 'mbrandoliniy');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Glen', 'O''Feeny', '1970-01-13', '785-409-4470', 'gofeenyz@vinaora.com', '290 Florence Street', 'Topeka', 'KS', '66611', 'gofeenyz');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Chilton', 'Arstingall', '1954-01-30', '214-906-9621', 'carstingall10@virginia.edu', '19 Straubel Trail', 'Houston', 'TX', '77005', 'carstingall10');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Hamilton', 'Stobo', '1997-03-19', '559-250-8666', 'hstobo11@marketwatch.com', '38653 Knutson Alley', 'Fullerton', 'CA', '92640', 'hstobo11');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Edita', 'Pharrow', '1979-09-03', '937-483-3386', 'epharrow12@angelfire.com', '2925 Schiller Parkway', 'Dayton', 'OH', '45432', 'epharrow12');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Trista', 'Luggar', '1971-06-02', '859-933-8398', 'tluggar13@istockphoto.com', '71 Caliangt Terrace', 'Lexington', 'KY', '40591', 'tluggar13');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Corrianne', 'Hallbord', '1966-11-01', '770-771-7731', 'challbord14@slashdot.org', '378 Raven Junction', 'Duluth', 'GA', '30195', 'challbord14');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Teddie', 'Downer', '1970-06-20', '806-900-3030', 'tdowner15@sakura.ne.jp', '20 Hollow Ridge Way', 'Lubbock', 'TX', '79405', 'tdowner15');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Harman', 'Jeacock', '1973-06-11', '404-905-8634', 'hjeacock16@chicagotribune.com', '2073 Monument Lane', 'Atlanta', 'GA', '30328', 'hjeacock16');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Fidelio', 'Hoffmann', '1980-03-28', '406-665-3403', 'fhoffmann17@nhs.uk', '0712 Hoepker Plaza', 'Missoula', 'MT', '59806', 'fhoffmann17');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Martica', 'Wrigley', '1995-04-23', '212-773-4458', 'mwrigley18@bbb.org', '53166 Swallow Point', 'New York City', 'NY', '10034', 'mwrigley18');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Robenia', 'Fernely', '1975-08-20', '757-457-2194', 'rfernely19@dropbox.com', '46072 Boyd Way', 'Norfolk', 'VA', '23514', 'rfernely19');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Gare', 'Juza', '1963-08-22', '763-493-9140', 'gjuza1a@statcounter.com', '31 Di Loreto Crossing', 'Monticello', 'MN', '55590', 'gjuza1a');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Harrison', 'Ogg', '1965-11-03', '918-760-8353', 'hogg1b@1und1.de', '2394 Calypso Circle', 'Tulsa', 'OK', '74141', 'hogg1b');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Lenette', 'Betterton', '1981-05-05', '336-186-6978', 'lbetterton1c@technorati.com', '88 Schiller Road', 'Greensboro', 'NC', '27409', 'lbetterton1c');
insert into Customers_List (Customer_FirstName, Customer_LastName, Customer_DateOfBirth, Customer_Phone, Customer_Email, Customer_Address, Customer_City, Customer_State, Customer_ZipCode, Customer_UserName) values ('Berty', 'Ord', '1969-01-01', '213-334-8151', 'bord1d@livejournal.com', '252 Ronald Regan Circle', 'Santa Ana', 'CA', '92705', 'bord1d');
